spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: thinhle
    password: themilkyway
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sendGrid:
    apiKey: ${SENDGRID_API_KEY}
    templateId: d-cd323b342c6c4d06958a41f4f39d9a22
    fromEmail: alexenderthk56789@gmail.com
    verificationLink: http://localhost:8080/user/confirm-email

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: dev-secret-key